### ISSUE TITLE
Escolher um tema para o TCC

### ISSUE THREAD

**Issue by ReinanHS** [ReinanHS/tcc-bsi-ifs#2]
## Qual tema escolher

Recomenda-se que o aluno faça uma breve pesquisa sobre os trabalhos já existentes e que sejam mais relevantes na área. Com isso, é possível saber se algum assunto já está saturado ou se tem pouca bibliografia.

### Quais disciplinas passei com maior êxito?

- (**10**) Algorítimos e Estrutura de Dados 1
- (**10**) Programação web 1
- (**10**) Programação web 2
- (**9.7**) Paradigma Orientado a objetos
- (**9.5**) Projeto de banco de dados
- (**9.0**) Programação para dispositivos móveis

### Qual disciplina eu me interessei e pesquisei mais sobre?

- Programação web 2
- Programação para dispositivos móveis
- Gerencia de projeto

## Qual docente trabalha na área escolhida?

1. [FRANCISCO](https://sig.ifs.edu.br/sigaa/public/docente/portal.jsf?siape=1579241)
2. [JEAN](https://sig.ifs.edu.br/sigaa/public/docente/portal.jsf?siape=2505768)
3. [WILHELM](https://sig.ifs.edu.br/sigaa/public/docente/portal.jsf?siape=1843549)
4. [JOAO PAULO](https://sig.ifs.edu.br/sigaa/public/docente/portal.jsf?siape=3237830)
5. [GEORGE](https://sig.ifs.edu.br/sigaa/public/docente/portal.jsf?siape=3310600)

**Comment by ReinanHS** [comment]
Após realizar um pequeno estudo, o assunto que mais me chamou a atenção foi o desenvolvimento de um sistema de ensino. Com base nisso, também quero que o sistema educacional seja semelhante ao [Duolingo](https://www.duolingo.com).

Para reforçar a minha escolha, em uma pesquisa no Google foi verificado que:

> Existem atualmente mais de 700.000 estudantes inscritos em cursos universitários de computação por ano. Os empregos de programadores estão a tornar-se cada vez mais escassos. Com isso é crucial que as crianças obtenham uma educação em programação no início da vida.

O desenvolvimento dessa ferramenta desse nível ajudaria muitos alunos do IFS campos Lagarto, pois permitiria que eles possam utilizar uma ferramenta de aprendizado baseada em jogos. Ao invés de métodos tradicionais de sala de aula, como palestras e projetos práticos.

Dito isso, o tema escolhido foi: **Desenvolvimento e avaliação de um sistema de E-Learning para o ensino de linguagens de programação**

**Comment by ReinanHS** [comment]
Após revisar o que foi discutido na última reunião. Percebe se que existe uma necessidade de não deixar o tema abrangente.

Perguntas que devem ser respondidas:

- Porque fazer o desenvolvimento e não a utilização de uma ferramenta já existente?
- Onde seria usado essa ferramenta?

**Comment by ReinanHS** [comment]
O tema geral teve que ser alterado para um tema onde houvesse a flexibilidade de poder utilizar soluções já existentes.  Dessa forma o tema ficou assim:

> O uso e avaliação de um sistema de e-learning no ensino de linguagens de programação.

Existem alguns sites que posso citar como exemplo onde é usado ferramentas para auxiliar e ajudar no ensino de programação:

- [Exercism](https://exercism.org/)
- [Hackerrank](https://www.hackerrank.com)

Se durante o desenvolvimento do TCC houver algum impedimento ou por falta de tempo será possível utilizar essas ferramentas ao invés de fazer o desenvolvimento de uma totalmente do zero.

**Comment by frchico** [comment]
Engraçado como o seu tema/ideia cruza com o de Leandro.

**Comment by ReinanHS** [comment]
> Engraçado como o seu tema/ideia cruza com o de Leandro.

Verdade, os dois temas estão muito parecidos.

Quando eu fui fazer essa reformulação no tema eu pensei a respeito da ideia da criação de um servidor GIT. Para fazer automações usando técnicas de Devops. Mas se você parar para ver de certa forma, isso voltaria a combinar com o tema de ensino de programação no IFS.

**Comment by ReinanHS** [comment]
@frchico tem algum problema as ideias estarem semelhantes? Acredito que no final a solução implementada talvez sejam diferentes

**Comment by frchico** [comment]
> @frchico tem algum problema as ideias estarem semelhantes? Acredito que no final a solução implementada talvez sejam diferentes

Não há problema, desde que você faça algo diferente dele. Por exemplo, ele vai citar algumas dificuldades no projeto dele e isso virá como contribuições futuras. Dai vc pega uma delas (ou mais de uma) e resolve, gerando assim, outro tcc.
