### ISSUE TITLE
Não está exibindo o ano da referência.

### ISSUE THREAD

**Issue by frchico** [ReinanHS/tcc-bsi-ifs#6]
https://github.com/ReinanHS/tcc-bsi-ifs/blob/1b6ffc8121e0b987dd661e7453119b477d6e398a/article/introducao.md?plain=1#L5

**Comment by frchico** [comment]
Sugestão: Adicionar a tag "Referência" ou algo do tipo para categorizar este erro. Depois adiciona um bot que faz isso automaticamente ;)

**Comment by ReinanHS** [comment]
Vou preparar um pull request com essa correção
